# Generated by Django 5.1.1 on 2024-09-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storychapter',
            old_name='chapter',
            new_name='story',
        ),
    ]
