# Generated by Django 5.1.1 on 2024-09-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_rename_chapter_storychapter_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='curr_node',
            new_name='current_node',
        ),
        migrations.RenameField(
            model_name='interaction',
            old_name='chapter',
            new_name='story',
        ),
    ]
