# Generated by Django 5.1.1 on 2024-09-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_curr_node_interaction_current_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storychapter',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_nodes', to='stories.storychapter'),
        ),
    ]
