# Generated by Django 5.1.1 on 2024-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_storychapter_parent_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychapter',
            name='chapter_number',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
